#ifndef __SHT31_H_
#define __SHT31_H

//SHT31 operation command
#define MEASUREMENT_ONE_SHOT_CS_MSB 0x2c
#define MEASUREMENT_ONE_SHOT_CS_LSB_H 0x06
#define MEASUREMENT_ONE_SHOT_CS_LSB_M 0x0d
#define MEASUREMENT_ONE_SHOT_CS_LSB_L 0x10

#define MEASUREMENT_ONE_SHOT_NCS_MSB 0x24
#define MEASUREMENT_ONE_SHOT_NCS_LSB_H 0x00
#define MEASUREMENT_ONE_SHOT_NCS_LSB_M 0x0b
#define MEASUREMENT_ONE_SHOT_NCS_LSB_L 0x16

#define SOFT_RESET 0x30a2
#define CLEAR_STATUS_REG 0x3041

#endif
